package main

import (
	"encoding/csv"
	"encoding/json"
	"encoding/xml"
	"errors"
	"flag"
	"fmt"
	"os"
	"path"
	"strconv"
	"strings"
	"time"
)

func printUsage() {

	fmt.Println("Usage: map2bbc [flags] <mapfile> <outputfile>")
	fmt.Println("Flags:")
	flag.PrintDefaults()
}

func exportMap(mapfile string, outfile string, packed bool) error {

	worldPath := path.Dir(mapfile)
	worldBytes, err := os.ReadFile(mapfile)

	if err != nil {

		return err
	}

	var world World
	err = json.Unmarshal(worldBytes, &world)

	if err != nil {

		return err
	}

	if len(world.Maps) == 0 {

		return errors.New("no maps")
	}

	f, err := os.Create(outfile)

	if err != nil {

		return err
	}

	defer f.Close()

	fmt.Fprintln(f, "; Auto-generated by map2bbc on", time.Now().Format("Mon, 2 Jan at 15:04"))
	fmt.Fprintln(f)
	fmt.Fprintln(f, "NUM_SCREENS =", len(world.Maps))

	// If we are writing Mountain Panic packed format, write some header data
	if packed {

		fmt.Fprintln(f)
		writePanicHeader(f)
		fmt.Fprintln(f)
		fmt.Fprintln(f, ".mapData:")
		for i := range len(world.Maps) {

			fmt.Fprintf(f, "  ; Screen %d\n", i)
			fmt.Fprintln(f, "  EQUB &00")
			fmt.Fprintln(f, "  EQUB &00")
			fmt.Fprintln(f, "  EQUB &00")
			fmt.Fprintln(f, "  EQUB &00,&00, &00, &00")
			fmt.Fprintln(f, "  EQUB &00")
		}
		fmt.Fprintln(f)
		fmt.Fprintln(f, ".screenTable:")
		for i := range len(world.Maps) {

			fmt.Fprintf(f, "  EQUW screen%dData\n", i)
		}
		fmt.Fprintln(f)
	}

	// Now loop over the world and write out the level data
	for i, v := range world.Maps {

		mapBytes, err := os.ReadFile(worldPath + "/" + v.Filename)

		if err != nil {

			return err
		}

		var tilemap TileMap
		err = xml.Unmarshal(mapBytes, &tilemap)

		if err != nil {

			return err
		}

		fmt.Fprintf(f, ".screen%dData:\n", i)

		// The CSV reader expects no ',' at the end of a line, so remove those
		trimmed := strings.ReplaceAll(tilemap.Data, ",\n", "\n")
		reader := csv.NewReader(strings.NewReader(trimmed))
		records, err := reader.ReadAll()

		for _, i := range records {

			rowBytes := make([]byte, 0)

			for _, j := range i {

				thisByte, err := strconv.Atoi(j)

				if err != nil {

					return err
				}

				rowBytes = append(rowBytes, byte(thisByte))
			}

			outputStr := "  EQUB "

			if packed {

				packedRowBytes, err := packLine(rowBytes)

				if err != nil {

					return err
				}

				for _, k := range packedRowBytes {

					// TODO: OR _bitCollidable etc when required
					outputStr += fmt.Sprintf("&%02X,", k)
				}

				outputStr, _ = strings.CutSuffix(outputStr, ",")

			} else {

				for _, k := range rowBytes {

					outputStr += fmt.Sprintf("&%02X", k)
				}

				outputStr, _ = strings.CutSuffix(outputStr, ",")
			}

			fmt.Fprintln(f, outputStr)
		}

		fmt.Fprintln(f)
	}

	if packed {

		writePanicFooter(f)
	}

	return nil
}

func main() {

	packed := flag.Bool("p", false, "Output in Mountain Panic packed format")

	flag.Parse()

	if flag.NArg() != 2 {

		printUsage()
		return
	}

	err := exportMap(flag.Arg(0), flag.Arg(1), *packed)

	if err != nil {

		fmt.Printf("Error exporting: %v\n", err)
	}
}
